print("Welcome to the tip calculator")
amount = float(input("What was the total bill? $"))
percentage = float(input("What percentage tip would you like to give? 10, 12 or 15? "))
total = amount + (amount * (percentage/100))
persons = int(input("How many people to split the bill? "))
print(f"Each person should pay: ${round(total/persons,2)}") 
